name: Bunnyshell - Stop Preview Environment
concurrency: bns-start-stop-${{ github.event.issue.number }}
on:
  issue_comment:
    types: [created, edited]
jobs:
  start:
    name: Stop Environment
    uses: bunnyshell/workflows/.github/workflows/stop-env.yaml@840efd407ae0c37f11d60f7d6a8a505eed4386a0
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      env-name: 'ArgoCD PR #${{ github.event.issue.number }}'
      allowed-users: ${{ vars.BUNNYSHELL_ALLOWED_USERS }}
      comment-on-pr: true
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
